### ISSUE TITLE
error

### ISSUE THREAD

**Issue by theshowmustgolangon** [c-zhou/yahs#2]
Hi,

I am running the tool with bam output file from Arima genomics pipeline, and pseudohap style assembly from 10x genomics.
But I found that this happens, and it seems something wrong in memory.
Could you give me any suggestion please?

[I::main] dump hic links to binary file yahs.out.bin
*** Error in `/work/tools/yahs/yahs': double free or corruption (fasttop): 0x0000000001fef610 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x2ab912b55489]
/work/tools/yahs/yahs[0x412bb4]
/work/tools/yahs/yahs[0x4317a8]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2ab912af63d5]
/work/tools/yahs/yahs[0x4021a9]
======= Memory map: ========
00400000-00467000 r-xp 00000000 fe:1e55c 144125879188990391              /work/tools/yahs/yahs
00667000-00668000 r--p 00067000 fe:1e55c 144125879188990391              /work/tools/yahs/yahs
00668000-0066c000 rw-p 00068000 fe:1e55c 144125879188990391              /work/tools/yahs/yahs
0066c000-0066d000 rw-p 00000000 00:00 0 
01997000-02006000 rw-p 00000000 00:00 0                                  [heap]
2ab912182000-2ab9121a4000 r-xp 00000000 fd:00 100667902                  /usr/lib64/ld-2.17.so
2ab9121a4000-2ab9121a8000 rw-p 00000000 00:00 0 
2ab9121cf000-2ab9121d4000 rw-p 00000000 00:00 0 
2ab9123a3000-2ab9123a4000 r--p 00021000 fd:00 100667902                  /usr/lib64/ld-2.17.so
2ab9123a4000-2ab9123a5000 rw-p 00022000 fd:00 100667902                  /usr/lib64/ld-2.17.so
2ab9123a5000-2ab9123a6000 rw-p 00000000 00:00 0 
2ab9123a6000-2ab9124a7000 r-xp 00000000 fd:00 100667917                  /usr/lib64/libm-2.17.so
2ab9124a7000-2ab9126a6000 ---p 00101000 fd:00 100667917                  /usr/lib64/libm-2.17.so
2ab9126a6000-2ab9126a7000 r--p 00100000 fd:00 100667917                  /usr/lib64/libm-2.17.so
2ab9126a7000-2ab9126a8000 rw-p 00101000 fd:00 100667917                  /usr/lib64/libm-2.17.so
2ab9126a8000-2ab9126bd000 r-xp 00000000 fd:00 100668244                  /usr/lib64/libz.so.1.2.7
2ab9126bd000-2ab9128bc000 ---p 00015000 fd:00 100668244                  /usr/lib64/libz.so.1.2.7
2ab9128bc000-2ab9128bd000 r--p 00014000 fd:00 100668244                  /usr/lib64/libz.so.1.2.7
2ab9128bd000-2ab9128be000 rw-p 00015000 fd:00 100668244                  /usr/lib64/libz.so.1.2.7
2ab9128be000-2ab9128d3000 r-xp 00000000 fd:00 100663369                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2ab9128d3000-2ab912ad2000 ---p 00015000 fd:00 100663369                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2ab912ad2000-2ab912ad3000 r--p 00014000 fd:00 100663369                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2ab912ad3000-2ab912ad4000 rw-p 00015000 fd:00 100663369                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
2ab912ad4000-2ab912c96000 r-xp 00000000 fd:00 100667909                  /usr/lib64/libc-2.17.so
2ab912c96000-2ab912e96000 ---p 001c2000 fd:00 100667909                  /usr/lib64/libc-2.17.so
2ab912e96000-2ab912e9a000 r--p 001c2000 fd:00 100667909                  /usr/lib64/libc-2.17.so
2ab912e9a000-2ab912e9c000 rw-p 001c6000 fd:00 100667909                  /usr/lib64/libc-2.17.so
2ab912e9c000-2ab912ea1000 rw-p 00000000 00:00 0 
2ab912ea1000-2ab912ea3000 r-xp 00000000 fd:00 100667915                  /usr/lib64/libdl-2.17.so
2ab912ea3000-2ab9130a3000 ---p 00002000 fd:00 100667915                  /usr/lib64/libdl-2.17.so
2ab9130a3000-2ab9130a4000 r--p 00002000 fd:00 100667915                  /usr/lib64/libdl-2.17.so
2ab9130a4000-2ab9130a5000 rw-p 00003000 fd:00 100667915                  /usr/lib64/libdl-2.17.so
2ab914000000-2ab914021000 rw-p 00000000 00:00 0 
2ab914021000-2ab918000000 ---p 00000000 00:00 0 
7ffcc042f000-7ffcc0453000 rw-p 00000000 00:00 0                          [stack]
7ffcc056b000-7ffcc056d000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
/var/spool/torque/mom_priv/jobs/5454962.apollo-acf.SC: line 72: 150539 Aborted                 (core dumped) $YAHS $ASSEMBLY_LOCATION/$SAMPLE/$SAMPLE.fasta $BAM_LOCATION/$BAM_FILE $OUTPUT_DIR/$LABEL\_$SAMPLE

**Comment by c-zhou** [comment]
Hi there,

Thanks very much for using YaHS. There is a bug in processing BAM files. I updated the code and has checked it in. I also made a pre-release for v1.1. You might want to give it a try. Please do let me know if you still have problems.

By the way, there is a new parameter `-q` (10 by default) for mapping quality filtering in this version - for BAM files only. In general, with higher quality filtering thresholds, the scaffolding results will be more reliable.

Best,
Chenxi

**Comment by c-zhou** [comment]
One more thing - in case you are not aware - the BAM file needs to be sorted by read names.

Chenxi

**Comment by theshowmustgolangon** [comment]
@c-zhou Hi, Thank you for your quick reply! I checked the version of YaHS, and it is already v.1.1. As I said, the BAM files are from Arima genomics pipeline, so I think I need to check the sorting process. Thank you!

**Comment by c-zhou** [comment]
Hi @theshowmustgolangon, 

I committed some changes to the repo earlier today to fix a bug in processing BAM files after you reported the issue. Even if it says the version is 1.1, you still need to update the code and rebuild. The current release v1.1a contains the latest updates. 

Also, it is recommended to mark duplicates before feeding to YaHS (as well as many other Hi-C scaffolding tools), which I think is not part of the Arima genomics pipeline.

Best,
Chenxi

**Comment by theshowmustgolangon** [comment]
@c-zhou Hi, I ran it again with the latest code, and I found that the same errors happened. Would it be better approach to check sorting process with the name when preprocessing Hi-C reads?

**Comment by c-zhou** [comment]
Hi @theshowmustgolangon, I updated the code to print more information during processing BAM files. It should have some outputs like `[I::dump_links_from_bam_file] 1 million records processed, 499979 read pairs` telling you how many BAM records were processed and how many read pairs were found. I also fixed a potential bug when there are unpaired reads or secondary or supplementary records in the BAM file - although there shouldn't be any if Arima's mapping pipeline was used. Please pull the latest code and rebuild.

Another straightforward way is to convert the BAM file to a BED file - which could also be served as the input for SALSA2. Here is how I usually do it `samtools view -@4 -u -F3332 ${markdup_bam} | bedtools bamtobed | sort -k4,4 --parallel=8 -S16G > ${markdup_bed}` 

Best,
Chenxi

**Comment by c-zhou** [comment]
Hi @theshowmustgolangon, I am going to close this issue now. Please let me know if you still have problems. Thanks, Chenxi

**Comment by theshowmustgolangon** [comment]
@c-zhou Hi! I was still experiencing the bugs, but I am still stick to the tool.
I am planing to assembly genomes using the variety of tools such as here, YAHS and SALSA2, but I am curious which ways to compare the two tools each other with output genome? I think it's not enough to do with contiguity only because better contiguity but with more errors could not be meaningful. Do I have to move for checking accuracy of genomes?

Thank you.

**Comment by c-zhou** [comment]
Thanks for your patience @theshowmustgolangon.

I would be happy to have a check if you could post the log. Also, you will need a BED file if want to try SALSA2. The input BED file to SALSA2 can be used by YaHS too. If the BAM error persists, using BED might be a good idea.

To check the accuracy of the scaffolding results, you might want to do a Hi-C contact map. There are plenty of ways to do it. The `scripts/run_yahs.sh` script shows an example for using Juicer_tools.

In terms of comparison, I do not have much experience either but would suggest giving QUAST a try, although it runs best with a ground truth reference genome which you might not have.

Best,
Chenxi
